### ISSUE TITLE
#ask bisa dipakai berkali2 tanpa clear cache

### ISSUE THREAD

**Issue by trialmemberl** [TUNBudi06/thepakv4#1]
Ini apa bisa dipake trus2an bang tnpa delete sama sekali... Soalnya filenya kayak auto kesimpen ke quickbms

**Comment by TUNBudi06** [comment]
Ini bisa clear cache dengan quit bro.jadi kalo misalnya mau clear cache langsung aja di quit.kalo masih mau edit file .dat tinggal CTRL + C
